const FRUITS_DATA = [
  { "w": "Apple", "file": "apple.png", "emoji": "🍎", "th": "แอปเปิ้ล" },
  { "w": "Banana", "file": "banana.png", "emoji": "🍌", "th": "กล้วย" },
  { "w": "Orange", "file": "orange.png", "emoji": "🍊", "th": "ส้ม" },
  { "w": "Strawberry", "file": "strawberry.png", "emoji": "🍓", "th": "สตรอเบอร์รี่" },
  { "w": "Grape", "file": "grape.png", "emoji": "🍇", "th": "องุ่น" },
  { "w": "Watermelon", "file": "watermelon.png", "emoji": "🍉", "th": "แตงโม" },
  { "w": "Pineapple", "file": "pineapple.png", "emoji": "🍍", "th": "สับปะรด" },
  { "w": "Mango", "file": "mango.png", "emoji": "🥭", "th": "มะม่วง" },
  { "w": "Papaya", "file": "papaya.png", "emoji": "🥭", "th": "มะละกอ" },
  { "w": "Coconut", "file": "coconut.png", "emoji": "🥥", "th": "มะพร้าว" },
  { "w": "Durian", "file": "durian.png", "emoji": "🍈", "th": "ทุเรียน" },
  { "w": "Mangosteen", "file": "mangosteen.png", "emoji": "🍇", "th": "มังคุด" },
  { "w": "Lemon", "file": "lemon.png", "emoji": "🍋", "th": "มะนาว" },
  { "w": "Peach", "file": "peach.png", "emoji": "🍑", "th": "ลูกพีช" },
  { "w": "Cherry", "file": "cherry.png", "emoji": "🍒", "th": "เชอร์รี่" },
  { "w": "Blueberry", "file": "blueberry.png", "emoji": "🫐", "th": "บลูเบอร์รี่" },
  { "w": "Avocado", "file": "avocado.png", "emoji": "🥑", "th": "อะโวคาโด" },
  { "w": "Kiwi", "file": "kiwi.png", "emoji": "🥝", "th": "กีวี่" },
  { "w": "Pear", "file": "pear.png", "emoji": "🍐", "th": "ลูกแพร์" },
  { "w": "Melon", "file": "melon.png", "emoji": "🍈", "th": "เมลอน" },
  { "w": "Pomegranate", "file": "pomegranate.png", "emoji": "🍎", "th": "ทับทิม" },
  { "w": "Dragon Fruit", "file": "dragon_fruit.png", "emoji": "🐉", "th": "แก้วมังกร" },
  { "w": "Lychee", "file": "lychee.png", "emoji": "🍒", "th": "ลิ้นจี่" },
  { "w": "Rambutan", "file": "rambutan.png", "emoji": "🌳", "th": "เงาะ" }
];
