const PLACES_DATA = [
  { "w": "School", "file": "school.png", "emoji": "🏫", "th": "โรงเรียน" },
  { "w": "Hospital", "file": "hospital.png", "emoji": "🏥", "th": "โรงพยาบาล" },
  { "w": "Zoom", "file": "zoom.png", "emoji": "💻", "th": "ห้องประชุมออนไลน์" },
  { "w": "Supermarket", "file": "supermarket.png", "emoji": "🛒", "th": "ซูเปอร์มาร์เก็ต" },
  { "w": "Library", "file": "library.png", "emoji": "📚", "th": "ห้องสมุด" },
  { "w": "Airport", "file": "airport.png", "emoji": "✈️", "th": "สนามบิน" },
  { "w": "Park", "file": "park.png", "emoji": "🌳", "th": "สวนสาธารณะ" },
  { "w": "Gym", "file": "gym.png", "emoji": "🏋️", "th": "โรงยิม" },
  { "w": "Restaurant", "file": "restaurant.png", "emoji": "🍽️", "th": "ร้านอาหาร" },
  { "w": "Cinema", "file": "cinema.png", "emoji": "🎬", "th": "โรงภาพยนตร์" },
  { "w": "Museum", "file": "museum.png", "emoji": "🏛️", "th": "พิพิธภัณฑ์" },
  { "w": "Police Station", "file": "police_station.png", "emoji": "👮", "th": "สถานีตำรวจ" },
  { "w": "Fire Station", "file": "fire_station.png", "emoji": "🚒", "th": "สถานีดับเพลิง" },
  { "w": "Beach", "file": "beach.png", "emoji": "🏖️", "th": "ชายหาด" },
  { "w": "Bank", "file": "bank.png", "emoji": "💰", "th": "ธนาคาร" },
  { "w": "Post Office", "file": "post_office.png", "emoji": "✉️", "th": "ที่ทำการไปรษณีย์" },
  { "w": "Zoo", "file": "zoo.png", "emoji": "🦁", "th": "สวนสัตว์" },
  { "w": "Bakery", "file": "bakery.png", "emoji": "🍞", "th": "ร้านเบเกอรี่" },
  { "w": "Amusement Park", "file": "amusement_park.png", "emoji": "🎢", "th": "สวนสนุก" },
  { "w": "Gas Station", "file": "gas_station.png", "emoji": "⛽", "th": "ปั๊มน้ำมัน" },
  { "w": "Coffee Shop", "file": "coffee_shop.png", "emoji": "☕", "th": "ร้านกาแฟ" },
  { "w": "Playground", "file": "playground.png", "emoji": "🛝", "th": "สนามเด็กเล่น" },
  { "w": "Farm", "file": "farm.png", "emoji": "🚜", "th": "ฟาร์ม" },
  { "w": "Hotel", "file": "hotel.png", "emoji": "🏨", "th": "โรงแรม" }
];
